name: Build and Deploy Microservices

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up JDK for building Spring Boot projects
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: 21
        distribution: 'temurin'

     # Step 3: Ensure mvnw scripts are executable
    - name: Set Executable Permissions for mvnw
      run: |
        chmod +x */mvnw
    
    # Step 4: Build and package each microservice
    - name: Build Microservices
      run: |
        for service in Apigateway Category Order Payment Product Registry User; do
          echo "Building $service..."
          cd $service
          ./mvnw clean package -DskipTests
          cd ..
        done
